http:
  port: 8080

apiEndpoints:
  customer:
    host: localhost
    paths: /customers/*
  product:
    host: localhost
    paths: /products/*
  order:
    host: localhost
    paths: /orders/*

serviceEndpoints:
  customerService:
    url: 'http://localhost:3002'
  productService:
    url: 'http://localhost:3001'
  orderService:
    url: 'http://localhost:3003'

policies: 
  - basic-auth
  - cors
  - log
  - proxy
  - jwt

pipelines:
  default:
    policies:
      - jwt:
          action:
            secret: 'yourSecretKey'
            algorithms: ['HS256']
            credentialsRequired: true
            requestProperty: 'user'  

      - cors:
          - action:
              origins: ['*']
              methods: ['GET', 'POST', 'PUT', 'DELETE']
              headers: ['Authorization', 'Content-Type']
              credentials: true

      - log:
          - action:
              message: 'Request from ${req.connection.remoteAddress}'

      - proxy:
          - action:
              serviceEndpoint: customerService
              changeOrigin: true
              condition:
                name: 'path'
                match: '/customers/*'
      - proxy:
          - action:
              serviceEndpoint: productService
              changeOrigin: true
              condition:
                name: 'path'
                match: '/products/*'
      - proxy:
          - action:
              serviceEndpoint: orderService
              changeOrigin: true
              condition:
                name: 'path'
                match: '/orders/*' 